Add Github API for release action

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,11 +33,11 @@ jobs:
             -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
             "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases/tags/${{ github.ref }}")
           echo $RESPONSE
-          RELEASE_ID=$(echo $RESPONSE | jq -r '.id')
-          if [ "$RELEASE_ID" = "null" ]; then
-            echo "Release with tag '${{ github.ref }}' not found."
-            exit 1
-          fi
+          #RELEASE_ID=$(echo $RESPONSE | jq -r '.id')
+          #if [ "$RELEASE_ID" = "null" ]; then
+          #  echo "Release with tag '${{ github.ref }}' not found."
+          #  exit 1
+          #fi
           echo "::set-output name=release_id::$RELEASE_ID"
 
       - name: Update Release
